spring.application.name=tasks

##DEV
#spring.config.import=configserver:https://api.inevolving.inovasoft.tech/config/
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true

#PROD
spring.config.import=configserver:http://config-service:8099